sonar.projectKey=edulearn-frontend
sonar.projectName=EduLearn Frontend
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/*.spec.ts,**/*.test.ts

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
